from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.agents.graph import build_agent_graph
from app.agents.state import AgentState
from app.core.config import settings
from app.core.database import get_db
from app.llm.client import get_llm_client
from app.models.user import User
from app.nlp.pipeline import analyze_text
from app.schemas.assistant import (
    AgenticResponse,
    AssistantRequest,
    AssistantResponse,
)
from app.security.dependencies import get_current_user


router = APIRouter()


SYSTEM_PROMPT = """
You are HelioSL, a renewable energy assistant for Sri Lanka.

For this development phase:
- provide general renewable energy explanations;
- do not claim access to official live regulations;
- do not claim access to the user's solar or energy history unless
  that data is explicitly provided in the prompt;
- do not invent sources;
- clearly state uncertainty;
- do not give dangerous electrical repair instructions.

Keep answers concise and useful.
"""


@router.post(
    "/agentic",
    response_model=AgenticResponse,
)
def run_agentic_assistant(
    data: AssistantRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> AgenticResponse:
    analysis = analyze_text(data.message)

    initial_state: AgentState = {
        "user_id": current_user.id,
        "original_query": data.message,
        "normalized_query": analysis[
            "normalized_query"
        ],
        "intent": analysis["intent"],
        "entities": analysis["entities"],
        "trace": [
            "NLP normalized the query, classified "
            "the intent and extracted entities."
        ],
    }

    result = build_agent_graph(db).invoke(
        initial_state
    )

    return AgenticResponse(
        message=result.get("final_answer", ""),
        intent=result.get("intent", "general"),
        entities=result.get("entities", {}),
        normalized_query=result.get(
            "normalized_query",
            data.message,
        ),
        selected_agents=result.get(
            "selected_agents",
            [],
        ),
        energy_result=result.get("energy_result"),
        knowledge_result=result.get(
            "knowledge_result"
        ),
        financial_result=result.get(
            "financial_result"
        ),
        sources=result.get("sources", []),
        safety_passed=result.get(
            "safety_passed",
            False,
        ),
        safety_notes=result.get(
            "safety_notes",
            [],
        ),
        trace=result.get("trace", []),
    )


@router.get("/health")
def assistant_health(
    current_user: User = Depends(get_current_user),
):
    client = get_llm_client()

    return {
        "status": (
            "healthy"
            if client.health()
            else "unavailable"
        ),
        "provider": settings.llm_provider,
        "model": settings.llm_model,
    }


@router.post(
    "/analyze",
    response_model=AssistantResponse,
)
def analyze_message(
    data: AssistantRequest,
    current_user: User = Depends(
        get_current_user
    ),
):
    analysis = analyze_text(
        data.message
    )

    client = get_llm_client()

    if not client.health():
        raise HTTPException(
            status_code=503,
            detail="LLM service is unavailable",
        )

    prompt = f"""
User query:
{analysis["normalized_query"]}

Detected intent:
{analysis["intent"]}

Extracted entities:
{analysis["entities"]}

Respond helpfully to the user.
"""

    content = client.generate(
        prompt=prompt,
        system_prompt=SYSTEM_PROMPT,
    )

    return AssistantResponse(
        message=content,
        intent=analysis["intent"],
        entities=analysis["entities"],
        normalized_query=analysis[
            "normalized_query"
        ],
        provider=settings.llm_provider,
        model=settings.llm_model,
        disclaimer=(
            "This response is generated by HelioSL's general "
            "LLM layer. Trusted retrieval and agent-based "
            "verification will be added in later phases."
        ),
    )
