"""create core energy data tables

Revision ID: b712cd2f0d0c
Revises: 
Create Date: 2026-09-18 09:45:08.322256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b712cd2f0d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('consumption_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('consumption_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bill_amount_lkr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'billing_month', name='uq_consumption_user_month')
    )
    op.create_index(op.f('ix_consumption_records_user_id'), 'consumption_records', ['user_id'], unique=False)
    op.create_table('energy_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('connection_type', sa.String(length=50), nullable=True),
    sa.Column('average_monthly_consumption_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_monthly_bill_lkr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_profiles_user_id'), 'energy_profiles', ['user_id'], unique=True)
    op.create_table('solar_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('capacity_kw', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('scheme', sa.String(length=100), nullable=True),
    sa.Column('panel_brand', sa.String(length=100), nullable=True),
    sa.Column('inverter_brand', sa.String(length=100), nullable=True),
    sa.Column('installer_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_systems_user_id'), 'solar_systems', ['user_id'], unique=True)
    op.create_table('solar_generation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=False),
    sa.Column('generation_month', sa.Date(), nullable=False),
    sa.Column('generation_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exported_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('imported_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solar_system_id'], ['solar_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solar_system_id', 'generation_month', name='uq_solar_generation_month')
    )
    op.create_index(op.f('ix_solar_generation_records_solar_system_id'), 'solar_generation_records', ['solar_system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_generation_records_solar_system_id'), table_name='solar_generation_records')
    op.drop_table('solar_generation_records')
    op.drop_index(op.f('ix_solar_systems_user_id'), table_name='solar_systems')
    op.drop_table('solar_systems')
    op.drop_index(op.f('ix_energy_profiles_user_id'), table_name='energy_profiles')
    op.drop_table('energy_profiles')
    op.drop_index(op.f('ix_consumption_records_user_id'), table_name='consumption_records')
    op.drop_table('consumption_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
